groups/urls.py
from django.urls import path

from groups.views import get_group, GroupEditView

app_name = 'groups'

urlpatterns = [
    path('<int:id>', get_group, name='group'),
    path('update/<int:id>', GroupEditView.as_view(), name='edit_group'),
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core_lms.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path

from students.views import StudentEditView, StudentDeleteView, \
    StudentCreateView, StudentListView

app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='list_students'),
    path('create', StudentCreateView.as_view(), name='create_students'),
    path('update/<int:id>', StudentEditView.as_view(),
         name='update_students'),
    path('delete/<int:id>', StudentDeleteView.as_view(),
         name='delete_students'),
]

students/models/lecture.py
from django.db import models


class Lecture(models.Model):
    name = models.CharField(max_length=32, null=False)
    students = models.ManyToManyField(
        to='students.Student',
        related_name='lectures',
        blank=True
    )

    class DifficultyLevel(models.IntegerChoices):
        LOW = 1, 'Low'
        NORMAL = 2, 'Normal'
        HIGH = 3, 'High'

    level = models.PositiveIntegerField(default=DifficultyLevel.LOW,
                                        choices=DifficultyLevel.choices)

students/models/student.py
import datetime
import random

from django.db import models
from django.urls import reverse
from faker import Faker

# Create your models here.
from core_lms.models import Person


class Student(Person):
    enroll_date = models.DateField(default=datetime.datetime.today)
    graduate_date = models.DateField(default=datetime.datetime.today)
    inn = models.PositiveIntegerField(unique=True, null=True)
    group = models.ForeignKey(
        to='groups.Group',
        null=True,
        on_delete=models.SET_NULL,
        related_name='students'
    )

    @classmethod
    def generate_students(cls, count):
        faker = Faker()

        for _ in range(count):
            s = Student()
            s.first_name = faker.first_name()
            s.last_name = faker.last_name()
            s.age = random.randint(18, 80)

            s.save()

    def __str__(self):
        return f"Student({self.id}) {self.first_name} {self.last_name} " \
               f"{self.age} {self.phone_number} " \
               f"{self.enroll_date} {self.graduate_date}"

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'

    def get_update_link(self):
        return reverse('students:update_students', kwargs={'id': self.id})

students/forms.py
import django_filters
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from students.models import Student


class StudentFilter(django_filters.FilterSet):
    class Meta:
        model = Student
        fields = {
            'first_name': ['iexact'],
            'last_name': ['iexact'],
            'age': ['exact'],
        }


class StudentBaseForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

    def clean(self):
        result = super().clean()

        enroll_date = self.cleaned_data['enroll_date']
        graduate_date = self.cleaned_data['graduate_date']

        if enroll_date > graduate_date:
            raise ValidationError("Enroll date cannot be less "
                                  "than gradate date")

        return result

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']

        has_phone_number_qs = Student.objects.filter(
            phone_number=phone_number
        )

        if self.instance:
            has_phone_number_qs = has_phone_number_qs.exclude(
                id=self.instance.id
            )

        if has_phone_number_qs.exists():
            raise ValidationError("Phone number is not unique")

        return phone_number


class StudentCreateForm(StudentBaseForm):
    pass


class StudentUpdateForm(StudentBaseForm):
    class Meta:
        model = Student
        exclude = ['age']

students/views.py
# Create your views here.
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView, DeleteView, CreateView, ListView

from students.forms import StudentCreateForm, StudentUpdateForm, StudentFilter
from students.models import Student


class StudentListView(ListView):
    model = Student
    template_name = 'students/list_students.html'
    paginate_by = 5

    def get_filter(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return StudentFilter(data=self.request.GET, queryset=queryset)

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.select_related('group__headman').order_by('-id')
        filter_ = self.get_filter(queryset)
        return filter_.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filter()

        # paginator = Paginator(self.get_queryset(), 5)
        # page_number = self.request.GET.get('page', '1')
        # page_obj = paginator.page(int(page_number))
        # context['page_obj'] = page_obj

        return context


class StudentCreateView(CreateView):
    model = Student
    success_url = reverse_lazy('students:list_students')
    form_class = StudentCreateForm
    template_name = 'students/create_student.html'


class StudentEditView(UpdateView):
    model = Student
    success_url = reverse_lazy('students:list_students')
    form_class = StudentUpdateForm
    template_name = 'students/edit_student.html'
    pk_url_kwarg = 'id'


class StudentDeleteView(DeleteView):
    model = Student
    pk_url_kwarg = 'id'
    template_name = 'students/delete_student.html'
    success_url = reverse_lazy('students:list_students')


# Not used
def delete_student_no_confirmation(request, id):
    try:
        student = Student.objects.get(id=id)
        student.delete()
    except Student.DoesNotExist:
        pass
    return HttpResponseRedirect(reverse('students:list_students'))

students/templates/students/_students_list.html
    <table class="table table-striped">
        <tr>
            <th>First Name</th>
            <th class="text-red border-blue">Last Name</th>
            <th>Group</th>
            <th>Group Headman</th>
            <th>INN</th>
            <th></th>
        </tr>

        {% for student in students %}
            <tr>
                <td>{{ student.first_name|capfirst }}</td>
                <td>{{ student.last_name|title }}</td>
                <td>
                    {% if student.group_id %}
                        <a href="{% url 'groups:group' id=student.group_id %}">
                            {{ student.group.name }}
                        </a>
                    {% else %}
                        <i>Empty</i>
                    {% endif %}
                </td>
                <td>
                    {% if student.group_id and student.group.headman_id %}
                        {{ student.group.headman.name }}
                    {% endif %}
                </td>
                <td>{{ student.inn }}</td>
                <td>
                    <a href="{% url 'students:update_students' id=student.id %}">✎</a>
                    <a href="{% url 'students:delete_students' id=student.id %}">🗑</a>
                </td>
            </tr>
        {% endfor %}
    </table>

students/templates/students/create_student.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <p>
            <button type="submit">Create Student</button>
        </p>
    </form>
{% endblock %}

students/templates/students/delete_student.html
{% extends '_base.html' %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        <p>Do you want to delete student {{ object.name }}?</p>
        <p>
            <button class="btn btn-danger" type="submit">Delete</button>
            <a class="btn btn-info" href="{% url 'students:list_students' %}">Cancel</a>
        </p>
    </form>
{% endblock %}

students/templates/students/edit_student.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <p>
            <button type="submit">Update Student</button>
        </p>
    </form>
{% endblock %}

students/templates/students/list_students.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <form>
        <p>Search students</p>
        {{ filter.form|crispy }}
        <p>
            <button type="submit">Search</button>
        </p>
    </form>
    <br>
    <a href="{% url 'students:create_students' %}">Add new student</a><br>

    {% include 'students/_students_list.html' with students=object_list %}

    {% include '_pagination.html' %}
{% endblock %}