groups/urls.py
from django.urls import path

from groups.views import get_group, GroupEditView

app_name = 'groups'

urlpatterns = [
    path('<int:id>', get_group, name='group'),
    path('update/<int:id>', GroupEditView.as_view(), name='edit_group'),
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core_lms.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/models.py
import datetime
import random

from django.db import models
# Create your models here.
from django.urls import reverse
from faker import Faker


class Group(models.Model):
    name = models.CharField(max_length=64, null=False)
    course = models.CharField(max_length=64, null=False)
    start_date = models.DateField(default=datetime.datetime.today)
    headman = models.OneToOneField(
        to='students.Student',
        on_delete=models.SET_NULL,
        null=True,
        related_name='headed_group'
    )

    def __str__(self):
        return super().__str__() + f'({self.name} {self.course})'

    @classmethod
    def generate(cls, count):
        faker = Faker()
        for _ in range(count):
            group = Group()
            group.name = faker.job()
            group.course = str(random.randint(1, 10))
            group.start_date = (
                    datetime.datetime.today() -
                    datetime.timedelta(days=random.randint(1, 1000))
            )
            group.save()

    def get_absolute_url(self):
        return reverse('groups:group', kwargs={'id': self.id})

groups/forms.py
from django.forms import ModelForm

from groups.models import Group


class GroupBaseForm(ModelForm):
    class Meta:
        model = Group
        fields = '__all__'


class GroupUpdateForm(GroupBaseForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['headman'].queryset = \
            self.fields['headman'].queryset.filter(
                group_id=self.instance.id
            )

groups/views.py
from django.shortcuts import render, get_object_or_404
# Create your views here.
from django.views.generic import UpdateView

from groups.forms import GroupUpdateForm
from groups.models import Group


def get_group(request, id):
    group = get_object_or_404(Group, id=id)
    return render(
        request,
        'groups/group.html',
        {
            'group': group
        }
    )


class GroupEditView(UpdateView):
    model = Group
    form_class = GroupUpdateForm
    template_name = 'groups/edit_group.html'

    pk_url_kwarg = 'id'

groups/templates/groups/edit_group.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <p>
            <button type="submit">Update Group</button>
        </p>
    </form>

    <h3>Students</h3>

    {% with students=object.students.all %}
        {% include 'students/_students_list.html' %}
    {% endwith %}
{% endblock %}

groups/templates/groups/group.html
{% extends '_base.html' %}

{% block main %}
    <h2>Group {{ group.name }} | <a href="{% url 'groups:edit_group' id=group.id %}">[Edit]</a></h2>
    <table class="table">
        <tr>
            <th>Course</th>
            <td>{{ group.course }}</td>
        </tr>
        <tr>
            <th>Start Date</th>
            <td>{{ group.start_date }}</td>
        </tr>
        <tr>
            <th>Headman</th>
            <td>{{ group.headman.name }}</td>
        </tr>
    </table>

    <h3>Students</h3>

    {% with students=group.students.all %}
        {% include 'students/_students_list.html' %}
    {% endwith %}

{% endblock %}