accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy

from accounts.views import AccountRegister, AccountLogin, AccountEdit

app_name = 'accounts'

urlpatterns = [
    path('register', AccountRegister.as_view(), name='register'),
    path('login', AccountLogin.as_view(), name='login'),
    path('profile', AccountEdit.as_view(), name='profile'),
    path('logout', LogoutView.as_view(
        next_page=reverse_lazy('accounts:login')
    ), name='logout'),
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core_lms.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path

from students.views import StudentEditView, StudentDeleteView, \
    StudentCreateView, StudentListView

app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='list_students'),
    path('create', StudentCreateView.as_view(), name='create_students'),
    path('update/<int:id>', StudentEditView.as_view(),
         name='update_students'),
    path('delete/<int:id>', StudentDeleteView.as_view(),
         name='delete_students'),
]

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>STUDENTS</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">

    <style type="text/css">


    </style>
</head>
<body>
{% include '_header_menu.html' %}

<div class="container">
    {% include '_messages.html' %}
    {% block main %}
    {% endblock %}
</div>
</body>
</html>

templates/_header_menu.html
{#<a href="/">LMS</a> | <a href="{% url 'students:list_students' %}">Students</a>#}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <div class="container-fluid d-flex p-0">
            <a class="navbar-brand" href="/">LMS</a>
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{% url 'students:list_students' %}">Students</a>
                    </li>
{#                            <li class="nav-item">#}
{#                              <a class="nav-link" href="#">Link</a>#}
{#                            </li>#}
{#                            <li class="nav-item dropdown">#}
{#                              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">#}
{#                                Dropdown#}
{#                              </a>#}
{#                              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#                                <li><a class="dropdown-item" href="#">Action</a></li>#}
{#                                <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#                                <li><hr class="dropdown-divider"></li>#}
{#                                <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#                              </ul>#}
{#                            </li>#}
{#                            <li class="nav-item">#}
{#                              <a class="nav-link disabled">Disabled</a>#}
{#                            </li>#}
                </ul>
                <ul class="navbar-nav me-2 mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:profile' %}">{{ user.username }}'s Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Sign Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Sign In</a>
                        </li>
                    {% endif %}
                </ul>
{#                      <form class="d-flex">#}
{#                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
{#                        <button class="btn btn-outline-success" type="submit">Search</button>#}
{#                      </form>#}
            </div>
        </div>
    </div>
</nav>

templates/_messages.html
{% if messages %}
    {% for message in messages %}
        <p{% if message.tags %}
            class="alert alert-{{ message.tags }} {% if message.tags == 'error' %}alert-danger{% endif %}"{% endif %} role="alert">{{ message }}</p>
    {% endfor %}
{% endif %}

templates/_pagination.html
{% load query_transform %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?{% query_transform_tag page=1 %}">&laquo; first</a>
            <a href="?{% query_transform_tag page=page_obj.previous_page_number %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?{% query_transform_tag page=page_obj.next_page_number %}">next</a>
            <a href="?{% query_transform_tag page=page_obj.paginator.num_pages %}">last &raquo;</a>
        {% endif %}
    </span>
</div>

templates/index.html
{% extends '_base.html' %}
{% block main %}
    <h1 class="p-0">Welcome to LMS!</h1>
{% endblock %}